# Generated by Django 5.2 on 2025-04-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorados',
            name='photo',
            field=models.ImageField(default='photos/default.bmp', upload_to='photos'),
        ),
    ]
