# Generated by Django 5.2 on 2025-04-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentees', '0003_scheduleavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorados',
            name='token',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
